global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["app:8000"]

  - job_name: "node"
    static_configs:
      - targets: [ "127.0.0.1:9100" ]